import { newDb } from 'pg-mem';
import { drizzle } from 'drizzle-orm/node-postgres';
import type { Pool } from 'pg';
import * as schema from '../db/schema';
import type { AppDatabase } from '../db/types';

export interface SeedData {
  seasons: any[];
  weeks: any[];
}

export interface TestDbResult {
  orm: AppDatabase;
  drizzleDb: AppDatabase;
  pool: Pool;
  seedData?: SeedData;
}

const builderProxyCache = new WeakMap<object, any>();

function wrapQueryBuilder<T extends object>(builder: T): T {
  const existing = builderProxyCache.get(builder);
  if (existing) {
    return existing;
  }

  const proxy = new Proxy(builder as any, {
    get(target, prop, receiver) {
      if (prop === 'get') {
        return async () => {
          const limited = typeof target.limit === 'function' ? target.limit(1) : target;
          const rows = await limited.execute();
          return Array.isArray(rows) ? rows[0] : rows;
        };
      }

      if (prop === 'all') {
        return async () => {
          const rows = await target.execute();
          return Array.isArray(rows) ? rows : [rows];
        };
      }

      if (prop === 'run') {
        return async () => {
          const result = await target.execute();

          if (Array.isArray(result)) {
            return { changes: result.length };
          }

          return result;
        };
      }

      const value = Reflect.get(target, prop, receiver);

      if (typeof value === 'function') {
        return (...args: any[]) => {
          const result = value.apply(target, args);
          if (result && typeof result === 'object' && typeof (result as any).execute === 'function') {
            return wrapQueryBuilder(result);
          }
          return result;
        };
      }

      return value;
    },
  });

  builderProxyCache.set(builder, proxy);
  return proxy;
}

function wrapOrmWithLegacyCompat(orm: AppDatabase): AppDatabase {
  return new Proxy(orm as any, {
    get(target, prop, receiver) {
      const value = Reflect.get(target, prop, receiver);

      if (typeof value !== 'function') {
        return value;
      }

      return (...args: any[]) => {
        const result = value.apply(target, args);
        if (result && typeof result === 'object' && typeof (result as any).execute === 'function') {
          return wrapQueryBuilder(result);
        }
        return result;
      };
    },
  }) as AppDatabase;
}

// Full Postgres DDL — kept aligned with bootstrap-postgres-schema.js for test fidelity.
// pg-mem executes these synchronously so setupTestDb stays synchronous.
const SCHEMA_DDL = [
  'CREATE TABLE IF NOT EXISTS sessions (sid TEXT PRIMARY KEY, sess JSONB NOT NULL, expire TIMESTAMP NOT NULL)',
  'CREATE TABLE IF NOT EXISTS participant (strava_athlete_id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, active BOOLEAN NOT NULL DEFAULT TRUE, is_admin BOOLEAN NOT NULL DEFAULT FALSE, weight DOUBLE PRECISION, weight_updated_at TIMESTAMPTZ)',
  'CREATE TABLE IF NOT EXISTS season (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, start_at BIGINT NOT NULL, end_at BIGINT NOT NULL, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)',
  'CREATE TABLE IF NOT EXISTS segment (strava_segment_id TEXT PRIMARY KEY, name TEXT NOT NULL, distance DOUBLE PRECISION, average_grade DOUBLE PRECISION, start_latitude DOUBLE PRECISION, start_longitude DOUBLE PRECISION, end_latitude DOUBLE PRECISION, end_longitude DOUBLE PRECISION, city TEXT, state TEXT, country TEXT, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, metadata_updated_at TIMESTAMPTZ, total_elevation_gain DOUBLE PRECISION, climb_category BIGINT)',
  'CREATE TABLE IF NOT EXISTS week (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, season_id BIGINT NOT NULL REFERENCES season(id), week_name TEXT NOT NULL, strava_segment_id TEXT NOT NULL REFERENCES segment(strava_segment_id), required_laps BIGINT NOT NULL DEFAULT 1, start_at BIGINT NOT NULL, end_at BIGINT NOT NULL, multiplier BIGINT NOT NULL DEFAULT 1, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, notes TEXT DEFAULT \'\')',
  'CREATE TABLE IF NOT EXISTS activity (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, week_id BIGINT NOT NULL REFERENCES week(id), strava_athlete_id TEXT NOT NULL REFERENCES participant(strava_athlete_id), strava_activity_id TEXT NOT NULL, start_at BIGINT NOT NULL, device_name TEXT, validation_status TEXT DEFAULT \'valid\', validation_message TEXT, validated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, athlete_weight DOUBLE PRECISION)',
  'CREATE TABLE IF NOT EXISTS segment_effort (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, activity_id BIGINT NOT NULL REFERENCES activity(id), strava_segment_id TEXT NOT NULL REFERENCES segment(strava_segment_id), strava_effort_id TEXT, effort_index BIGINT NOT NULL, elapsed_seconds BIGINT NOT NULL, start_at BIGINT NOT NULL, pr_achieved BIGINT, average_watts DOUBLE PRECISION, average_heartrate DOUBLE PRECISION, max_heartrate DOUBLE PRECISION, average_cadence DOUBLE PRECISION, device_watts BOOLEAN)',
  'CREATE TABLE IF NOT EXISTS result (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, week_id BIGINT NOT NULL REFERENCES week(id), strava_athlete_id TEXT NOT NULL REFERENCES participant(strava_athlete_id), activity_id BIGINT REFERENCES activity(id), total_time_seconds BIGINT NOT NULL, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)',
  'CREATE TABLE IF NOT EXISTS participant_token (strava_athlete_id TEXT PRIMARY KEY REFERENCES participant(strava_athlete_id) ON DELETE CASCADE, access_token TEXT NOT NULL, refresh_token TEXT NOT NULL, expires_at BIGINT NOT NULL, scope TEXT, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)',
  'CREATE TABLE IF NOT EXISTS deletion_request (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, strava_athlete_id TEXT NOT NULL, requested_at TIMESTAMPTZ NOT NULL, status TEXT DEFAULT \'pending\', completed_at TIMESTAMPTZ)',
  'CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, name TEXT NOT NULL, executed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)',
  'CREATE TABLE IF NOT EXISTS webhook_event (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payload TEXT NOT NULL, processed BIGINT, error_message TEXT, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)',
  'CREATE TABLE IF NOT EXISTS webhook_subscription (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, verify_token TEXT NOT NULL, subscription_payload TEXT, subscription_id BIGINT, last_refreshed_at TIMESTAMPTZ)',
  'CREATE TABLE IF NOT EXISTS explorer_campaign (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, start_at BIGINT NOT NULL, end_at BIGINT NOT NULL, display_name TEXT, rules_blurb TEXT, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)',
  'CREATE TABLE IF NOT EXISTS explorer_destination (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, explorer_campaign_id BIGINT NOT NULL REFERENCES explorer_campaign(id) ON DELETE CASCADE, strava_segment_id TEXT NOT NULL, source_url TEXT, cached_name TEXT, display_label TEXT, display_order BIGINT NOT NULL DEFAULT 0, surface_type TEXT, category TEXT, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)',
  'CREATE TABLE IF NOT EXISTS explorer_destination_match (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, explorer_campaign_id BIGINT NOT NULL REFERENCES explorer_campaign(id) ON DELETE CASCADE, explorer_destination_id BIGINT NOT NULL REFERENCES explorer_destination(id) ON DELETE CASCADE, strava_athlete_id TEXT NOT NULL REFERENCES participant(strava_athlete_id) ON DELETE CASCADE, strava_activity_id TEXT NOT NULL, matched_at BIGINT NOT NULL, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)',
  'CREATE TABLE IF NOT EXISTS explorer_destination_pin (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, explorer_campaign_id BIGINT NOT NULL REFERENCES explorer_campaign(id) ON DELETE CASCADE, explorer_destination_id BIGINT NOT NULL REFERENCES explorer_destination(id) ON DELETE CASCADE, strava_athlete_id TEXT NOT NULL REFERENCES participant(strava_athlete_id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)',
  'CREATE TABLE IF NOT EXISTS chain_wax_period (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, started_at BIGINT NOT NULL, ended_at BIGINT, total_distance_meters DOUBLE PRECISION NOT NULL DEFAULT 0, created_at BIGINT NOT NULL)',
  'CREATE TABLE IF NOT EXISTS chain_wax_activity (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, period_id BIGINT NOT NULL REFERENCES chain_wax_period(id), strava_activity_id TEXT NOT NULL UNIQUE, strava_athlete_id TEXT NOT NULL, distance_meters DOUBLE PRECISION NOT NULL, activity_start_at BIGINT NOT NULL, created_at BIGINT NOT NULL)',
  'CREATE TABLE IF NOT EXISTS chain_wax_puck (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, started_at BIGINT NOT NULL, wax_count BIGINT NOT NULL DEFAULT 0, is_current BOOLEAN NOT NULL DEFAULT TRUE, created_at BIGINT NOT NULL)',
  'CREATE INDEX IF NOT EXISTS idx_sessions_expire ON sessions (expire)',
  'CREATE INDEX IF NOT EXISTS idx_week_season ON week (season_id)',
  'CREATE INDEX IF NOT EXISTS idx_activity_status ON activity (validation_status)',
  'CREATE INDEX IF NOT EXISTS idx_activity_week_participant ON activity (week_id, strava_athlete_id)',
  'CREATE INDEX IF NOT EXISTS idx_segment_effort_activity ON segment_effort (activity_id)',
  'CREATE INDEX IF NOT EXISTS idx_result_participant ON result (strava_athlete_id)',
  'CREATE INDEX IF NOT EXISTS idx_result_week ON result (week_id)',
  'CREATE INDEX IF NOT EXISTS idx_result_week_athlete ON result (week_id, strava_athlete_id)',
  'CREATE INDEX IF NOT EXISTS idx_participant_token_participant ON participant_token (strava_athlete_id)',
  'CREATE INDEX IF NOT EXISTS idx_webhook_event_created ON webhook_event (created_at)',
  'CREATE INDEX IF NOT EXISTS idx_explorer_campaign_window ON explorer_campaign (start_at, end_at)',
  'CREATE INDEX IF NOT EXISTS idx_explorer_destination_campaign ON explorer_destination (explorer_campaign_id)',
  'CREATE INDEX IF NOT EXISTS idx_explorer_destination_segment ON explorer_destination (strava_segment_id)',
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_explorer_destination_campaign_segment ON explorer_destination (explorer_campaign_id, strava_segment_id)',
  'CREATE INDEX IF NOT EXISTS idx_explorer_match_campaign_athlete ON explorer_destination_match (explorer_campaign_id, strava_athlete_id)',
  'CREATE INDEX IF NOT EXISTS idx_explorer_match_activity ON explorer_destination_match (strava_activity_id)',
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_explorer_match_unique ON explorer_destination_match (explorer_campaign_id, explorer_destination_id, strava_athlete_id)',
  'CREATE INDEX IF NOT EXISTS idx_explorer_pin_campaign_athlete ON explorer_destination_pin (explorer_campaign_id, strava_athlete_id)',
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_explorer_pin_unique ON explorer_destination_pin (explorer_campaign_id, explorer_destination_id, strava_athlete_id)',
  'CREATE INDEX IF NOT EXISTS idx_chain_wax_activity_period ON chain_wax_activity (period_id)',
  'CREATE INDEX IF NOT EXISTS idx_chain_wax_activity_strava_id ON chain_wax_activity (strava_activity_id)',
];

export function setupTestDb(options?: { seed?: boolean }): TestDbResult {
  const { seed = true } = options || {};

  // Each test file gets its own isolated in-memory Postgres instance.
  const memDb = newDb();

  // Bootstrap schema synchronously via pg-mem's direct interface.
  for (const stmt of SCHEMA_DDL) {
    memDb.public.none(stmt);
  }

  let seedData: SeedData | undefined = undefined;

  if (seed) {
    // Seed synchronously via pg-mem's direct SQL interface so this function
    // stays synchronous and test files don't need async beforeAll just for setup.
    memDb.public.none('INSERT INTO participant (strava_athlete_id, name, active) VALUES (\'100\', \'Test User 1\', true)');
    memDb.public.none('INSERT INTO participant (strava_athlete_id, name, active) VALUES (\'200\', \'Test User 2\', true)');
    const testSeason = memDb.public.one('INSERT INTO season (name, start_at, end_at) VALUES (\'Test Season\', 1735689600, 1767225599) RETURNING *') as any;
    memDb.public.none('INSERT INTO segment (strava_segment_id, name) VALUES (\'1000\', \'Test Segment\')');
    const testWeek = memDb.public.one(`INSERT INTO week (season_id, week_name, strava_segment_id, required_laps, start_at, end_at) VALUES (${testSeason.id}, 'Test Week', '1000', 1, 1748736000, 1748793600) RETURNING *`) as any;
    const testActivity1 = memDb.public.one(`INSERT INTO activity (week_id, strava_athlete_id, strava_activity_id, start_at) VALUES (${testWeek.id}, '100', '${Math.floor(Math.random() * 1e9)}', 1748772000) RETURNING *`) as any;
    const testActivity2 = memDb.public.one(`INSERT INTO activity (week_id, strava_athlete_id, strava_activity_id, start_at) VALUES (${testWeek.id}, '200', '${Math.floor(Math.random() * 1e9)}', 1748775600) RETURNING *`) as any;
    memDb.public.none(`INSERT INTO result (week_id, strava_athlete_id, activity_id, total_time_seconds) VALUES (${testWeek.id}, '100', ${testActivity1.id}, 100)`);
    memDb.public.none(`INSERT INTO result (week_id, strava_athlete_id, activity_id, total_time_seconds) VALUES (${testWeek.id}, '200', ${testActivity2.id}, 200)`);
    seedData = { seasons: [testSeason], weeks: [testWeek] };
  }

  // Wire up Drizzle over the pg-mem pool adapter.
  const { Pool } = memDb.adapters.createPg();
  // drizzle/node-postgres passes query.types.getTypeParser for parameterized
  // queries; pg-mem does not implement that API, so strip it in tests.
  const proto = (Pool as any).prototype;
  if (!proto.__wmvPatchedAdaptQuery) {
    const originalAdaptQuery = proto.adaptQuery;
    const originalAdaptResults = proto.adaptResults;
    proto.adaptQuery = function patchedAdaptQuery(query: any, values: any) {
      if (query && typeof query === 'object' && 'types' in query) {
        const cloned = { ...query };
        delete cloned.types;
        return originalAdaptQuery.call(this, cloned, values);
      }
      return originalAdaptQuery.call(this, query, values);
    };
    proto.adaptResults = function patchedAdaptResults(query: any, res: any) {
      if (query && typeof query === 'object' && query.rowMode === 'array') {
        const base = originalAdaptResults.call(this, { ...query, rowMode: undefined }, res);
        const fieldNames = (res.fields || []).map((f: any) => f.name);
        return {
          ...base,
          rows: base.rows.map((row: Record<string, unknown>) => fieldNames.map((name: string) => row[name])),
          fields: fieldNames.map((name: string, idx: number) => ({
            name,
            tableID: 0,
            columnID: idx + 1,
            dataTypeID: 0,
            dataTypeSize: -1,
            dataTypeModifier: -1,
            format: 'text',
          })),
        };
      }
      return originalAdaptResults.call(this, query, res);
    };
    proto.__wmvPatchedAdaptQuery = true;
  }
  const pool = new Pool() as unknown as import('pg').Pool;
  const orm = wrapOrmWithLegacyCompat(drizzle(pool, { schema }) as AppDatabase);
  const drizzleDb = orm; // alias for backward compat

  return { orm, drizzleDb, pool, seedData };
}

// End the pool when a test file is done. Safe to call multiple times.
export async function teardownTestDb(pool: Pool): Promise<void> {
  try { await pool.end(); } catch { /* already closed */ }
}
