CREATE TABLE "activity" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"week_id" bigint NOT NULL,
	"strava_athlete_id" text NOT NULL,
	"strava_activity_id" text NOT NULL,
	"start_at" bigint NOT NULL,
	"device_name" text,
	"validation_status" text DEFAULT 'valid',
	"validation_message" text,
	"validated_at" timestamp with time zone DEFAULT now(),
	"created_at" timestamp with time zone DEFAULT now(),
	"athlete_weight" double precision
);
--> statement-breakpoint
CREATE TABLE "chain_wax_activity" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chain_wax_activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"period_id" bigint NOT NULL,
	"strava_activity_id" text NOT NULL,
	"strava_athlete_id" text NOT NULL,
	"distance_meters" double precision NOT NULL,
	"activity_start_at" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chain_wax_activity_strava_activity_id_unique" UNIQUE("strava_activity_id")
);
--> statement-breakpoint
CREATE TABLE "chain_wax_period" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chain_wax_period_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"started_at" bigint NOT NULL,
	"ended_at" bigint,
	"total_distance_meters" double precision DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chain_wax_puck" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chain_wax_puck_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"started_at" bigint NOT NULL,
	"wax_count" bigint DEFAULT 0 NOT NULL,
	"is_current" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "deletion_request" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deletion_request_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"strava_athlete_id" text NOT NULL,
	"requested_at" timestamp with time zone NOT NULL,
	"status" text DEFAULT 'pending',
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "explorer_campaign" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "explorer_campaign_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"start_at" bigint NOT NULL,
	"end_at" bigint NOT NULL,
	"display_name" text,
	"rules_blurb" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "explorer_destination" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "explorer_destination_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"explorer_campaign_id" bigint NOT NULL,
	"strava_segment_id" text NOT NULL,
	"source_url" text,
	"cached_name" text,
	"display_label" text,
	"display_order" bigint DEFAULT 0 NOT NULL,
	"surface_type" text,
	"category" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "explorer_destination_match" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "explorer_destination_match_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"explorer_campaign_id" bigint NOT NULL,
	"explorer_destination_id" bigint NOT NULL,
	"strava_athlete_id" text NOT NULL,
	"strava_activity_id" text NOT NULL,
	"matched_at" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "explorer_destination_pin" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "explorer_destination_pin_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"explorer_campaign_id" bigint NOT NULL,
	"explorer_destination_id" bigint NOT NULL,
	"strava_athlete_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "participant" (
	"strava_athlete_id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"active" boolean DEFAULT true NOT NULL,
	"is_admin" boolean DEFAULT false NOT NULL,
	"weight" double precision,
	"weight_updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "participant_token" (
	"strava_athlete_id" text PRIMARY KEY NOT NULL,
	"access_token" text NOT NULL,
	"refresh_token" text NOT NULL,
	"expires_at" bigint NOT NULL,
	"scope" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "result" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"week_id" bigint NOT NULL,
	"strava_athlete_id" text NOT NULL,
	"activity_id" bigint,
	"total_time_seconds" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "schema_migrations" (
	"version" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"executed_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "season" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "season_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"start_at" bigint NOT NULL,
	"end_at" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "segment" (
	"strava_segment_id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"distance" double precision,
	"average_grade" double precision,
	"start_latitude" double precision,
	"start_longitude" double precision,
	"end_latitude" double precision,
	"end_longitude" double precision,
	"city" text,
	"state" text,
	"country" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"metadata_updated_at" timestamp with time zone,
	"total_elevation_gain" double precision,
	"climb_category" bigint
);
--> statement-breakpoint
CREATE TABLE "segment_effort" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "segment_effort_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_id" bigint NOT NULL,
	"strava_segment_id" text NOT NULL,
	"strava_effort_id" text,
	"effort_index" bigint NOT NULL,
	"elapsed_seconds" bigint NOT NULL,
	"start_at" bigint NOT NULL,
	"pr_achieved" bigint,
	"average_watts" double precision,
	"average_heartrate" double precision,
	"max_heartrate" double precision,
	"average_cadence" double precision,
	"device_watts" boolean
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"sid" text PRIMARY KEY NOT NULL,
	"sess" jsonb NOT NULL,
	"expire" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "webhook_event" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "webhook_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"payload" text NOT NULL,
	"processed" bigint,
	"error_message" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "webhook_subscription" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "webhook_subscription_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"verify_token" text NOT NULL,
	"subscription_payload" text,
	"subscription_id" bigint,
	"last_refreshed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "week" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "week_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"season_id" bigint NOT NULL,
	"week_name" text NOT NULL,
	"strava_segment_id" text NOT NULL,
	"required_laps" bigint DEFAULT 1 NOT NULL,
	"start_at" bigint NOT NULL,
	"end_at" bigint NOT NULL,
	"multiplier" bigint DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"notes" text DEFAULT ''
);
--> statement-breakpoint
ALTER TABLE "activity" ADD CONSTRAINT "activity_week_id_week_id_fk" FOREIGN KEY ("week_id") REFERENCES "public"."week"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity" ADD CONSTRAINT "activity_strava_athlete_id_participant_strava_athlete_id_fk" FOREIGN KEY ("strava_athlete_id") REFERENCES "public"."participant"("strava_athlete_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chain_wax_activity" ADD CONSTRAINT "chain_wax_activity_period_id_chain_wax_period_id_fk" FOREIGN KEY ("period_id") REFERENCES "public"."chain_wax_period"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_destination" ADD CONSTRAINT "explorer_destination_explorer_campaign_id_explorer_campaign_id_fk" FOREIGN KEY ("explorer_campaign_id") REFERENCES "public"."explorer_campaign"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_destination_match" ADD CONSTRAINT "explorer_destination_match_explorer_campaign_id_explorer_campaign_id_fk" FOREIGN KEY ("explorer_campaign_id") REFERENCES "public"."explorer_campaign"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_destination_match" ADD CONSTRAINT "explorer_destination_match_explorer_destination_id_explorer_destination_id_fk" FOREIGN KEY ("explorer_destination_id") REFERENCES "public"."explorer_destination"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_destination_match" ADD CONSTRAINT "explorer_destination_match_strava_athlete_id_participant_strava_athlete_id_fk" FOREIGN KEY ("strava_athlete_id") REFERENCES "public"."participant"("strava_athlete_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_destination_pin" ADD CONSTRAINT "explorer_destination_pin_explorer_campaign_id_explorer_campaign_id_fk" FOREIGN KEY ("explorer_campaign_id") REFERENCES "public"."explorer_campaign"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_destination_pin" ADD CONSTRAINT "explorer_destination_pin_explorer_destination_id_explorer_destination_id_fk" FOREIGN KEY ("explorer_destination_id") REFERENCES "public"."explorer_destination"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_destination_pin" ADD CONSTRAINT "explorer_destination_pin_strava_athlete_id_participant_strava_athlete_id_fk" FOREIGN KEY ("strava_athlete_id") REFERENCES "public"."participant"("strava_athlete_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participant_token" ADD CONSTRAINT "participant_token_strava_athlete_id_participant_strava_athlete_id_fk" FOREIGN KEY ("strava_athlete_id") REFERENCES "public"."participant"("strava_athlete_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_week_id_week_id_fk" FOREIGN KEY ("week_id") REFERENCES "public"."week"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_strava_athlete_id_participant_strava_athlete_id_fk" FOREIGN KEY ("strava_athlete_id") REFERENCES "public"."participant"("strava_athlete_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_effort" ADD CONSTRAINT "segment_effort_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_effort" ADD CONSTRAINT "segment_effort_strava_segment_id_segment_strava_segment_id_fk" FOREIGN KEY ("strava_segment_id") REFERENCES "public"."segment"("strava_segment_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "week" ADD CONSTRAINT "week_season_id_season_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."season"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "week" ADD CONSTRAINT "week_strava_segment_id_segment_strava_segment_id_fk" FOREIGN KEY ("strava_segment_id") REFERENCES "public"."segment"("strava_segment_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_activity_status" ON "activity" USING btree ("validation_status");--> statement-breakpoint
CREATE INDEX "idx_activity_week_participant" ON "activity" USING btree ("week_id","strava_athlete_id");--> statement-breakpoint
CREATE INDEX "idx_chain_wax_activity_period" ON "chain_wax_activity" USING btree ("period_id");--> statement-breakpoint
CREATE INDEX "idx_chain_wax_activity_strava_id" ON "chain_wax_activity" USING btree ("strava_activity_id");--> statement-breakpoint
CREATE INDEX "idx_explorer_campaign_window" ON "explorer_campaign" USING btree ("start_at","end_at");--> statement-breakpoint
CREATE INDEX "idx_explorer_destination_campaign" ON "explorer_destination" USING btree ("explorer_campaign_id");--> statement-breakpoint
CREATE INDEX "idx_explorer_destination_segment" ON "explorer_destination" USING btree ("strava_segment_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_explorer_destination_campaign_segment" ON "explorer_destination" USING btree ("explorer_campaign_id","strava_segment_id");--> statement-breakpoint
CREATE INDEX "idx_explorer_match_campaign_athlete" ON "explorer_destination_match" USING btree ("explorer_campaign_id","strava_athlete_id");--> statement-breakpoint
CREATE INDEX "idx_explorer_match_activity" ON "explorer_destination_match" USING btree ("strava_activity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_explorer_match_unique" ON "explorer_destination_match" USING btree ("explorer_campaign_id","explorer_destination_id","strava_athlete_id");--> statement-breakpoint
CREATE INDEX "idx_explorer_pin_campaign_athlete" ON "explorer_destination_pin" USING btree ("explorer_campaign_id","strava_athlete_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_explorer_pin_unique" ON "explorer_destination_pin" USING btree ("explorer_campaign_id","explorer_destination_id","strava_athlete_id");--> statement-breakpoint
CREATE INDEX "idx_participant_token_participant" ON "participant_token" USING btree ("strava_athlete_id");--> statement-breakpoint
CREATE INDEX "idx_result_participant" ON "result" USING btree ("strava_athlete_id");--> statement-breakpoint
CREATE INDEX "idx_result_week" ON "result" USING btree ("week_id");--> statement-breakpoint
CREATE INDEX "idx_result_week_athlete" ON "result" USING btree ("week_id","strava_athlete_id");--> statement-breakpoint
CREATE INDEX "idx_segment_effort_activity" ON "segment_effort" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX "idx_sessions_expire" ON "sessions" USING btree ("expire");--> statement-breakpoint
CREATE INDEX "idx_webhook_event_created" ON "webhook_event" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_week_season" ON "week" USING btree ("season_id");